version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.api/Dockerfile
  
  catalogdb:
     image: mongo

volumes:
   mongo_data: